name: 获取最近两次提交的差距
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: 设置环境
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: 重新构建下载jar
        run: mvn clean install
      - name: 将本地的jar包拷贝到目标文件夹
        run: mvn dependency:copy -Dartifact=com.ai.review:ai-review-sdk:1.0 -DoutputDirectory=./libs
      - name: 运行自己的jar
        run: java -jar ./libs/ai-review-sdk-1.0.jar
        env:
          TOKEN: ${{secrets.API_KEY}}